### ISSUE TITLE
Jobs Page showing Job description at the top of the Page like a Session Flash Message

### ISSUE THREAD

**Issue by pravintargaryen** [proevo/pythondotorg#2361]
**Describe the bug**
When visiting a specific job page at https://www.python.org/jobs/{pageid} for example - https://www.python.org/jobs/7456/, the first few lines of Job Description appears at the top above the navbar with 'The Company' Template String  

**To Reproduce**
1. Go to 'https://www.python.org/jobs/7456/'
2. Scroll up to 'Top of the page above the navbar'
3. See error

**Expected behavior**
DOM loading as usual with the Navbar at the top and other components accordingly

**Screenshots**
![1](https://github.com/python/pythondotorg/assets/96950453/86cee793-d5c7-4d3d-8cc7-b651ff483226)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro for Workstations
 - Browser : Google Chrome
 - Version: 120.0.6099.225 (Official Build) (64-bit)

**Comment by joncle** [comment]
Should be fixed if https://github.com/python/pythondotorg/pull/2298 gets merged...

**Comment by Jalithc** [comment]
I'm going to work on this issue.But didn't appears at the top above the navbar with 'The Company' Template String.

**Comment by ddevdan** [comment]
hi @joncle, #2298 does not fix the issue 

https://www.python.org/jobs/7519/
![image](https://github.com/python/pythondotorg/assets/42525687/85b5c83c-d45d-43c7-907c-fb8a97590fa6)

**Comment by joncle** [comment]
Yeah... I'd noticed that @ddevdan - thanks for the reminder. I'm doing a few changes on the Job Board functionality over the course of this week so I'll sort this properly as I work through those.

**Comment by JacobCoffee** [comment]
Duplicate of #2020
