### ISSUE TITLE
Bug: Main Page and Download Python Source Still Reference 3.12.6

### ISSUE THREAD

**Issue by questionlp** [proevo/pythondotorg#2631]
### Describe the bug

With Python 3.12.7 released on 2 Oct 2024, the latest version listed in the Download block on the main page still lists 3.12.6. Also, the Downloads popup in the site navigation also references 3.12.6.

### To Reproduce

Downloads navigation popup

1. Open a web browser
2. Browse to <https://www.python.org>
3. Hover cursor over the **Downloads** navigation item

Downloads Latest

1. Open a web browser
2. Browse to <https://www.python.org>
3. Scroll down to the **Get Started** and **Downloads** blocks, Latests lists the previous version

### Expected behavior

In both locations, 3.12.7 should be listed as the latest version and should link to the appropriate [release page](https://www.python.org/downloads/release/python-3127/) or to the appropriate [release tarball](https://www.python.org/ftp/python/3.12.7/Python-3.12.7.tar.xz)

### URL to the issue

https://www.python.org/

### Screenshots

![image](https://github.com/user-attachments/assets/224d68ea-5fd3-40c9-862a-14b2e72fdd25)

![image](https://github.com/user-attachments/assets/fa2842f7-c57f-4991-84db-2c6aadb01019)

### Browsers

Firefox, Chrome

### Operating System

Linux

### Browser Version

130

**Comment by ned-deily** [comment]
@JacobCoffee, any ideas? Everything looks OK from the admin side and at least the generated homepage-downloads box shows 3.12.7. Cache issue? Generating the web page issue?

**Comment by JacobCoffee** [comment]
Not sure! I'm checking.

I believe this comes from from 
- [downloads/models.py:178](https://github.com/python/pythondotorg/blob/0d5432a04dbfb78b582c808856f912b412b1201b/downloads/models.py#L178)
- https://github.com/python/pythondotorg/blob/802aa1e9c7499fd178bad75b7768760ef4c0b049/templates/downloads/supernav.html#L11

**Comment by JacobCoffee** [comment]
I did purge the Fastly cache with no luck

**Comment by ned-deily** [comment]
I'm pretty sure we've had problems in the past with the download button not updating right away but I think it has been working fine in recent releases. Perhaps something was inadvertently broken by the recent website updates? In any case, it can wait until daylight.

**Comment by JacobCoffee** [comment]
If I dive in manually into the shell for this service and run that supernav update I get 3.12.7 :\

```
# Shell Plus Django Imports
from django.core.cache import cache
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import transaction
from django.db.models import Avg, Case, Count, F, Max, Min, Prefetch, Q, Sum, When
from django.utils import timezone
from django.urls import reverse
from django.db.models import Exists, OuterRef, Subquery
Python 3.12.6 (main, Sep 27 2024, 20:22:39) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> Release.objects.latest_python3()
<Release: Python 3.12.7>
>>> 
```

**Comment by JacobCoffee** [comment]
@ned-deily yeah recent deployments could be the reason. I'll do a bisect tomorrow and see if I can reproduce locally to find a root cause 🙃

**Comment by ned-deily** [comment]
Thanks, @JacobCoffee!  And thanks, @questionlp, for reporting it.

**Comment by questionlp** [comment]
@ned-deily @JacobCoffee No problem at all and thanks for taking a look at it so quickly. Much appreciated ^_^

**Comment by Tarunmadhav** [comment]
This is beyond frustrating! First, I can’t even download or access the Python modules I need half the time, the repository just refuses to respond or throws some ridiculous error. Then, after hours of wrestling with that, I’m stuck with Python 3.12.6, which is riddled with bugs! Seriously, how is this version even out in the wild?! Every time I try to run something, I struck with stupid errors like module not found on the most basic modules such as pandas pytorch tensorflow etc and all . I don’t have time to deal with a broken release and spend my day navigating errors . What is even the point of releasing an update if it’s going to break everything? Fix it or don't release it at all. It is displaying distutils error in code execution. I am able to execute in my laptop which has the older version (3.11.3),and on desktop it is was not being executed in my pc in spite being the latest version. Using of speech recognition module asking to install discord module in _init.main__ page of site packages  . Even the 3.11 family is also showing the same issues

**Comment by Mariatta** [comment]
@Tarunmadhav Your comment is off topic and unrelated. Your tone is hostile and not appreciated here.

The libraries you mentioned (pandas, pythorch, etc) are not part of Python standard library. You could ask elsewhere (like on stackoverflow) on how to install and use third party libraries. Moreover, this issue tracker is for issues related to the Python .org website, and not for the general usage of Python.

**Comment by JacobCoffee** [comment]
Resolved 

<img width="691" alt="image" src="https://github.com/user-attachments/assets/3e09184f-5780-40cf-b654-bc2c51aa8a6c">

So, we take the above code links and render them into a box and that box URL was not being properly purged even though it belongs to the application surrogate key.

Fix was to manually purge the *box* URL path
```
Purge Request Sent
www.python.org/box/supernav-python-downloads/

Purge ID
...
```

**Comment by questionlp** [comment]
I see the new version in the navigation popup/dropdown now, though the **Download** block further down the page is still showing 3.12.6.

![Screenshot_20241004_105641](https://github.com/user-attachments/assets/7f725733-3cc7-4340-8f76-212aa7b27c92)
